### ISSUE TITLE
Tiff file contains no page error for the test dataset?

### ISSUE THREAD

**Issue by grace-fengqing-yu** [erturklab/delivr_cfos#3]
Hi, very impressive work and thanks for providing the scripts for the end-to-end pipeline! Our group is trying to reproduce the results using the test dataset provided. But when I tried to run the script with the dataset, I met the "<tifffile.TiffFile 'downsampled_um_xxxxxx.tif'> contains no pages" error. Below are the full output, do you know the potential causes of this issue and how I can solve it? Thank you in advance for your help!

Loading config.json
Making /data/projects/deepneuronseg/Grace_files/DeLiVR/deliver_cfos/data/output/04_atlas_alignment/collection/
HOOK:OVERALL:6
Masking
HOOK:1:6:0:1
['/tmp/tmpe0oqvfnv/downsampled_um_z0000-0004.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0004-0008.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0008-0012.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0012-0016.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0016-0020.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0020-0024.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0024-0028.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0028-0032.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0032-0036.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0036-0040.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0040-0044.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0044-0048.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0048-0052.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0052-0056.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0056-0060.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0060-0064.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0064-0068.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0068-0072.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0072-0076.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0076-0080.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0080-0084.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0084-0088.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0088-0092.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0092-0096.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0096-0100.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0100-0104.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0104-0108.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0108-0112.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0112-0116.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0116-0120.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0120-0124.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0124-0128.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0128-0132.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0132-0136.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0136-0140.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0140-0144.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0144-0148.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0148-0152.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0152-0156.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0156-0160.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0160-0164.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0164-0168.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0168-0172.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0172-0176.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0176-0180.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0180-0184.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0184-0188.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0188-0192.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0192-0196.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0196-0200.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0200-0204.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0204-0208.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0208-0212.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0212-0216.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0216-0220.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0220-0224.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0224-0228.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0228-0232.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0232-0236.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0236-0240.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0240-0244.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0244-0248.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0248-0252.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0252-0256.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0256-0260.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0260-0264.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0264-0268.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0268-0272.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0272-0276.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0276-0280.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0280-0284.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0284-0288.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0288-0292.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0292-0296.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0296-0300.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0300-0304.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0304-0308.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0308-0312.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0312-0316.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0316-0320.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0320-0324.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0324-0328.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0328-0332.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0332-0336.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0336-0340.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0340-0344.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0344-0348.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0348-0352.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0352-0356.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0356-0360.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0360-0364.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0364-0368.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0368-0372.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0372-0376.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0376-0380.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0380-0384.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0384-0388.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0388-0392.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0392-0396.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0396-0400.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0400-0404.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0404-0408.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0408-0412.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0412-0416.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0416-0420.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0420-0424.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0424-0428.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0428-0432.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0432-0436.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0436-0440.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0440-0444.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0444-0448.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0448-0452.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0452-0456.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0456-0460.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0460-0464.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0464-0468.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0468-0472.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0472-0476.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0476-0480.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0480-0484.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0484-0488.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0488-0492.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0492-0496.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0496-0500.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0500-0504.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0504-0508.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0508-0512.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0512-0516.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0516-0520.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0520-0524.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0524-0528.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0528-0532.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0532-0536.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0536-0540.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0540-0544.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0544-0548.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0548-0552.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0552-0556.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0556-0560.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0560-0564.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0564-0568.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0568-0572.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0572-0576.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0576-0580.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0580-0584.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0584-0588.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0588-0592.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0592-0596.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0596-0600.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0600-0604.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0604-0608.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0608-0612.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0612-0616.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0616-0620.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0620-0624.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0624-0628.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0628-0632.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0632-0636.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0636-0640.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0640-0644.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0644-0648.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0648-0652.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0652-0656.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0656-0660.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0660-0664.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0664-0668.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0668-0672.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0672-0676.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0676-0680.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0680-0684.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0684-0688.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0688-0692.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0692-0696.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0696-0700.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0700-0704.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0704-0708.tif', '/tmp/tmpe0oqvfnv/downsampled_um_z0708-0712.tif']
<tifffile.TiffFile 'downsampled_um_z0000-0004.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0004-0008.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0008-0012.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0012-0016.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0016-0020.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0020-0024.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0024-0028.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0028-0032.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0032-0036.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0036-0040.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0040-0044.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0044-0048.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0048-0052.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0052-0056.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0056-0060.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0060-0064.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0064-0068.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0068-0072.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0072-0076.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0076-0080.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0080-0084.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0084-0088.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0088-0092.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0092-0096.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0096-0100.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0100-0104.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0104-0108.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0108-0112.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0112-0116.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0116-0120.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0120-0124.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0124-0128.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0128-0132.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0132-0136.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0136-0140.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0140-0144.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0144-0148.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0148-0152.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0152-0156.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0156-0160.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0160-0164.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0164-0168.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0168-0172.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0172-0176.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0176-0180.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0180-0184.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0184-0188.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0188-0192.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0192-0196.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0196-0200.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0200-0204.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0204-0208.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0208-0212.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0212-0216.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0216-0220.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0220-0224.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0224-0228.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0228-0232.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0232-0236.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0236-0240.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0240-0244.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0244-0248.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0248-0252.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0252-0256.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0256-0260.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0260-0264.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0264-0268.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0268-0272.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0272-0276.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0276-0280.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0280-0284.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0284-0288.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0288-0292.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0292-0296.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0296-0300.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0300-0304.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0304-0308.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0308-0312.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0312-0316.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0316-0320.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0320-0324.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0324-0328.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0328-0332.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0332-0336.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0336-0340.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0340-0344.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0344-0348.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0348-0352.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0352-0356.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0356-0360.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0360-0364.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0364-0368.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0368-0372.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0372-0376.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0376-0380.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0380-0384.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0384-0388.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0388-0392.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0392-0396.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0396-0400.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0400-0404.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0404-0408.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0408-0412.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0412-0416.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0416-0420.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0420-0424.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0424-0428.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0428-0432.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0432-0436.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0436-0440.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0440-0444.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0444-0448.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0448-0452.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0452-0456.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0456-0460.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0460-0464.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0464-0468.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0468-0472.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0472-0476.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0476-0480.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0480-0484.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0484-0488.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0488-0492.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0492-0496.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0496-0500.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0500-0504.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0504-0508.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0508-0512.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0512-0516.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0516-0520.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0520-0524.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0524-0528.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0528-0532.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0532-0536.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0536-0540.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0540-0544.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0544-0548.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0548-0552.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0552-0556.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0556-0560.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0560-0564.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0564-0568.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0568-0572.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0572-0576.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0576-0580.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0580-0584.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0584-0588.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0588-0592.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0592-0596.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0596-0600.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0600-0604.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0604-0608.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0608-0612.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0612-0616.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0616-0620.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0620-0624.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0624-0628.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0628-0632.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0632-0636.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0636-0640.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0640-0644.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0644-0648.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0648-0652.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0652-0656.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0656-0660.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0660-0664.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0664-0668.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0668-0672.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0672-0676.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0676-0680.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0680-0684.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0684-0688.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0688-0692.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0692-0696.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0696-0700.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0700-0704.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0704-0708.tif'> contains no pages
<tifffile.TiffFile 'downsampled_um_z0708-0712.tif'> contains no pages
/home/gyu/.conda/envs/DeLiVR_env/lib/python3.8/site-packages/tifffile/tifffile.py:1606: UserWarning: <tifffile.TiffWriter 'stack_resampled.tif'> writing zero size array to nonconformant TIFF
  warnings.warn(
Traceback (most recent call last):
  File "__main__.py", line 95, in <module>
    mouse_id, stack_shape = downsample_mask(settings, brain)
  File "/data/projects/deepneuronseg/Grace_files/DeLiVR/deliver_cfos/downsample/downsample_and_mask.py", line 274, in downsample_mask
    downsampled_stack_8bit = histogram_equalization_8b(downsampled_stack)
  File "/data/projects/deepneuronseg/Grace_files/DeLiVR/deliver_cfos/downsample/downsample_and_mask.py", line 178, in histogram_equalization_8b
    minval = round(np.percentile(stack.ravel(),1))
  File "<__array_function__ internals>", line 5, in percentile
  File "/home/gyu/.conda/envs/DeLiVR_env/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3867, in percentile
    return _quantile_unchecked(
  File "/home/gyu/.conda/envs/DeLiVR_env/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3986, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/home/gyu/.conda/envs/DeLiVR_env/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3564, in _ureduce
    r = func(a, **kwargs)
  File "/home/gyu/.conda/envs/DeLiVR_env/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4098, in _quantile_ureduce_func
    n = np.isnan(ap[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by MoritzNegwer** [comment]
Hi there, nice that you want to give DELiVR a shot! Judging from the error log you posted, it looks like there is an error in the downsampling step of the preprocessing, maybe with reading the test dataset. 

We are currently trying to reproduce this on our end. Meanwhile, could you please let us know the following infos? 
1) System you are running this on (Windows/Linux, Processor, RAM, Disk space) 
2) Are you running this from the Fiji plugin, docker container, or the code from this github repo? If you are running it via the Fiji plugin, can you save the entire log output (that includes the docker command) and post it here as .txt? If the latter two cases, can you please let us know the docker command you are using? 

Many thanks in advance and all the best,
Moritz

**Comment by MoritzNegwer** [comment]
Dear Grace, we checked and we think it's a python package version issue on your end. From the `File "/home/gyu/.conda/envs/DeLiVR_env/lib/python3.8/` in your error message, it looks like you are trying to run the code in a conda environment. I would guess that one or more of the packages doesn't match up with the ones we used. A good candidate would be tifffile. 

As a fix, I'd recommend to use our docker container, in which we have encapsulated the correct python environment for all parts of the pipeline to work together. Please find the docker container on our lab's website: https://www.discotechnologies.org/DELiVR/ . I will also upload the Dockerfile in short order so that you can compile your own.  If you are running this on a cluster that doesn't allow docker containers but is okay with Singularity/Apptainer, let me know and I'd be happy to send you our (pre-beta) Apptainer container. 

Hope this helps! All the best,
Moritz

**Comment by grace-fengqing-yu** [comment]
Hi Moritz, 

Thank you so much for your prompt reply! Yeah I was running it on Linux with a conda env, I'll check if it's because of our packages. Thanks for your help!

Best,
Grace
