### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///home/taz/.docker/desktop/docker.sock

### ISSUE THREAD

**Issue by neuronflow** [erturklab/delivr_cfos#4]
> Hi PedjaJJ,
> 
> Thanks for testing again. Just to check, you have re-downloaded the plugin (version 1.04) and container from [here](https://www.discotechnologies.org/DELiVR/) prior to install? We have been adding bugfixes throghout the day.
> 
> Judging from your error message, it looks as if the docker container is not starting, likely because of Linux-specific account permission issues. Can you please go through the following steps and let us know the results?
> 
> Step 1: Just to make sure that the docker daemon is correctly initialized: please run ` sudo systemctl start docker` (requires admin privileges).
> 
> Step 2: On Linux, normal users are not allowed to run docker commands, this requires administrator rights or being in a specific group. Can you please run `docker run --rm --runtime=nvidia nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi` and post the output?
> 
> Step 3: If you get a "cannot contact docker" error message, retry with `sudo docker run --rm --runtime=nvidia nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`. If that one works, your account currently does not have sufficient privileges to run docker commands. Please follow the steps outlined [here](https://docs.docker.com/engine/install/linux-postinstall/). Don't forget to log out and in again (or just reboot) at the end.
> 
> Step 4: Re-test with `docker run --rm --runtime=nvidia nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`. (without `sudo`). If it works this time, you should now have sufficient user rights - feel free to run the FIJI plugin and let us know what you find.

I am facing a similar issue right now on Ubuntu 22.04. after `running docker run --rm --runtime=nvidia nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`, I get the following error: 

Cannot connect to the Docker daemon at unix:///home/taz/.docker/desktop/docker.sock. Is the docker daemon running?.

I have added myself to the docker group though and have restarted my PC to test it and face the same issue. Please let me know if you are aware of a solution.

_Originally posted by @Tas-V in https://github.com/erturklab/delivr_cfos/issues/1#issuecomment-2070965060_

**Comment by neuronflow** [comment]
@Tas-V you seem to have a broken docker installation.

Which OS do you use?

Can you confirm that your docker daemon is running?

How did you install docker?

**Comment by MoritzNegwer** [comment]
Hi @Tas-V, sounds like the docker daemon is not running or you don't have access rights. It sounds like you're on Linux of some sort, for that we recommend to follow those instructions: https://docs.docker.com/engine/install/linux-postinstall/ 

Specifically, after the user rights assignment, if you want to start the docker daemon with the system, try running those two commands, then restart your PC: 
` sudo systemctl enable docker.service`
` sudo systemctl enable containerd.service`

To verify that the user rights assignment has worked, can you please run `docker run hello-world` and see what the output is? If that gives you the same error message as before, you can check whether it's a user rights issue by running the same as superuser with `sudo docker run hello-world` and see whether you get the same output. 

Please post the output here. If you have further questions in the meantime, let us know!

**Comment by Tas-V** [comment]
Hi @neuronflow 

My OS is Ubuntu 22.04 LTS. Here is the output for when I run `docker info`:

Client: Docker Engine - Community
 Version:    26.1.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
ERROR: Cannot connect to the Docker daemon at unix:///home/taz/.docker/desktop/docker.sock. Is the docker daemon running?
errors pretty printing info

When I sudo run docker info, the server connects. I installed docker using the dropbox link. I first attempted this on an existing docker build but had issues and removed both versions of docker from my computer and reran the dropbox docker install.

**Comment by Tas-V** [comment]
Hi @MoritzNegwer
 
Here is the output of running `docker run hello-world` after following the instructions for adding myself to the docker group as well as running the two commands and restarting my PC:

docker: Cannot connect to the Docker daemon at unix:///home/taz/.docker/desktop/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

Here is the output of running `sudo docker run hello-world `

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

Seems like it is still a user issue despite me being in the group. When I do `groups $USER`, I get docker as a group that I am a part of so I am still confused as to what the issue may be.

**Comment by MoritzNegwer** [comment]
Hi @Tas-V, thanks for your quick reaction. That sounds like it's a user access rights issue then. This could be due to the docker desktop context, which apparently only allows running containers via sudo. (the post-install steps only apply if you install docker via the command line, not via docker desktop). 

According to this forum discussion (https://forums.docker.com/t/unable-to-make-docker-run-without-sudo/138521) , you can list the contexts by typing `docker context ls`. If there is a "default" context available, you can switch to it by typing `docker context use default`. 

Please try the above steps, and post the output of `docker context ls` here. Please also verify whether the docker context switch was successful by re-running `docker run hello-world` at the end, and let us know whether it works without sudo now. Best of luck!

**Comment by Tas-V** [comment]
Hi @MoritzNegwer 

This solved the issue! Here is the output of `docker context ls`:

NAME              DESCRIPTION                               DOCKER ENDPOINT                                ERROR
default           Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                    
desktop-linux *   Docker Desktop                            unix:///home/taz/.docker/desktop/docker.sock   

I switched to default via `docker context use default` as you mentioned and now running `docker run hello-world` has the following output:

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/



I am now running into a separate issue when running the DELIVR pipeline via Fiji ImageJ and will open a new issue.

**Comment by neuronflow** [comment]
Sweet, thanks for reporting back.
